-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 15:33:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jarvis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jarvis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jarvis` DEFAULT CHARACTER SET utf8 ;
USE `jarvis` ;

-- -----------------------------------------------------
-- Table `jarvis`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Utilisateur` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `nom_u` VARCHAR(45) NULL,
  `prenom_u` VARCHAR(45) NULL,
  `date_de_naissance` DATE NULL,
  `email_u` VARCHAR(45) NULL,
  `sexe_u` VARCHAR(10) NULL,
  `mdp_u` VARCHAR(45) NULL,
  `lien_parente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_u`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Membre` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `lien_parente` INT NULL,
  `Utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`id_m`),
  INDEX `fk_Membre_Utilisateur_idx` (`Utilisateur_id_u` ASC),
  CONSTRAINT `fk_Membre_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_u`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Co-propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Co-propriétaire` (
  `id_co-pro` INT NOT NULL AUTO_INCREMENT,
  `lien_parente` INT NULL,
  `Utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`id_co-pro`),
  INDEX `fk_Co-propriétaire_Utilisateur1_idx` (`Utilisateur_id_u` ASC),
  CONSTRAINT `fk_Co-propriétaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_u`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Propriétaire` (
  `id_pro` INT NOT NULL AUTO_INCREMENT,
  `Utilisateur_id_u` INT NOT NULL,
  PRIMARY KEY (`id_pro`),
  INDEX `fk_Propriétaire_Utilisateur1_idx` (`Utilisateur_id_u` ASC),
  CONSTRAINT `fk_Propriétaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_u`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Appareils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Appareils` (
  `id_ap` INT NOT NULL AUTO_INCREMENT,
  `nom_ap` VARCHAR(255) NULL,
  `type_app` VARCHAR(255) NULL,
  PRIMARY KEY (`id_ap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Piece` (
  `idPiece` INT NOT NULL AUTO_INCREMENT,
  `nom_piece` VARCHAR(255) NULL,
  PRIMARY KEY (`idPiece`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Domicile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Domicile` (
  `id_d` INT NOT NULL AUTO_INCREMENT,
  `annee_construction` DATE NULL,
  `superficie` VARCHAR(45) NULL,
  PRIMARY KEY (`id_d`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Inviter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Inviter` (
  `Utilisateur_id_u` INT NOT NULL,
  `Propriétaire_id_pro` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_id_u`, `Propriétaire_id_pro`),
  INDEX `fk_Utilisateur_has_Propriétaire_Propriétaire1_idx` (`Propriétaire_id_pro` ASC),
  INDEX `fk_Utilisateur_has_Propriétaire_Utilisateur1_idx` (`Utilisateur_id_u` ASC),
  CONSTRAINT `fk_Utilisateur_has_Propriétaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_u`)
    REFERENCES `jarvis`.`Utilisateur` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Propriétaire_Propriétaire1`
    FOREIGN KEY (`Propriétaire_id_pro`)
    REFERENCES `jarvis`.`Propriétaire` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Se trouver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Se trouver` (
  `Appareils_id_ap` INT NOT NULL,
  `Piece_idPiece` INT NOT NULL,
  PRIMARY KEY (`Appareils_id_ap`, `Piece_idPiece`),
  INDEX `fk_Appareils_has_Piece_Piece1_idx` (`Piece_idPiece` ASC),
  INDEX `fk_Appareils_has_Piece_Appareils1_idx` (`Appareils_id_ap` ASC),
  CONSTRAINT `fk_Appareils_has_Piece_Appareils1`
    FOREIGN KEY (`Appareils_id_ap`)
    REFERENCES `jarvis`.`Appareils` (`id_ap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appareils_has_Piece_Piece1`
    FOREIGN KEY (`Piece_idPiece`)
    REFERENCES `jarvis`.`Piece` (`idPiece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Contenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Contenir` (
  `Piece_idPiece` INT NOT NULL,
  `Domicile_id_d` INT NOT NULL,
  PRIMARY KEY (`Piece_idPiece`, `Domicile_id_d`),
  INDEX `fk_Piece_has_Domicile_Domicile1_idx` (`Domicile_id_d` ASC),
  INDEX `fk_Piece_has_Domicile_Piece1_idx` (`Piece_idPiece` ASC),
  CONSTRAINT `fk_Piece_has_Domicile_Piece1`
    FOREIGN KEY (`Piece_idPiece`)
    REFERENCES `jarvis`.`Piece` (`idPiece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piece_has_Domicile_Domicile1`
    FOREIGN KEY (`Domicile_id_d`)
    REFERENCES `jarvis`.`Domicile` (`id_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis`.`Avoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis`.`Avoir` (
  `Propriétaire_id_pro` INT NOT NULL,
  `Domicile_id_d` INT NOT NULL,
  PRIMARY KEY (`Propriétaire_id_pro`, `Domicile_id_d`),
  INDEX `fk_Propriétaire_has_Domicile_Domicile1_idx` (`Domicile_id_d` ASC),
  INDEX `fk_Propriétaire_has_Domicile_Propriétaire1_idx` (`Propriétaire_id_pro` ASC),
  CONSTRAINT `fk_Propriétaire_has_Domicile_Propriétaire1`
    FOREIGN KEY (`Propriétaire_id_pro`)
    REFERENCES `jarvis`.`Propriétaire` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propriétaire_has_Domicile_Domicile1`
    FOREIGN KEY (`Domicile_id_d`)
    REFERENCES `jarvis`.`Domicile` (`id_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
